###### Filtering the consensus linakge map #########
### This script takes the Littorina saxatilis linkage map 
### generated by Eva Koch and filters it to remove any contigs
### which are >2cM from the mean map positon. In addition, due
### to inversions on LG14 & LG10, the markers from an old map
### will be used for these linkage groups.
### James Reeve - Göteborgs universitet
### 01/07/2021

### Preperation
rm(list = ls())
options(stringsAsFactors = FALSE)
dev.off()

### Packages
library(tidyverse)
library(ggpubr)

### Upload data
# Crab map - note this has been filtered by Alan Le Moan
LG.crab <- read.table("Map_filtrated.txt", header = T)
# Consensus map
LG.cons <- read.table("ConsensusMaps.txt", header = T)

### Formatting maps to get the same columns ####
### I will use the notation of the crab map
#     contig = contig ID
#     pos = physical position of map marker (bp)
#     av = map position of marker (cM)
#     LG = linkage group

# Split Marker ID for consensus map
tmp <- strsplit(LG.cons$Marker, "_")
LG.cons$contig <- sapply(tmp, `[[`, 1)
LG.cons$pos <- as.numeric(sapply(tmp, `[[`, 2))
rm(tmp)

# Rename LG flag in crab map
LG.crab$LG <- paste0("LG", LG.crab$LG)

# Rename column for 'Consensus.Position'
colnames(LG.cons)[3] <- "av"


########## Example #############
LG.cons$contig[LG.cons$contig %in% LG.crab$contig][1]

tmp1 <- LG.cons[LG.cons$contig == "Contig39332",]
tmp2 <- LG.crab[LG.crab$contig == "Contig39332",]
###############################
### Calculate mean map position per contig ####

# Add mean map position to data
# and calculate distance of each marker from the mean
LG.cons2 <- LG.cons %>% group_by(LG, contig) %>%
  mutate(avgMP = mean(av), deltaMP = abs(mean(av) - av))
LG.crab2 <- LG.crab %>% group_by(LG, contig) %>%
  mutate(avgMP = mean(av), deltaMP = abs(mean(av) - av))

# Remove all markers > 2cM from mean map position
LG.cons2 <- LG.cons2[LG.cons2$deltaMP <= 2,]
LG.crab2 <- LG.crab2[LG.crab2$deltaMP <= 2,]

# Number of markers lost
paste("Consensus map lost", nrow(LG.cons) - nrow(LG.cons2), "markers")
paste("Consensus map lost", nrow(LG.crab) - nrow(LG.crab2), "markers")



### Replace LG10 & LG14 with old map markers ####

# Remove 'Marker' column from LG.cons2
tmp <- LG.cons2[,-1]

# Remove LG10 & LG14
tmp2 <- tmp[tmp$LG != "LG10" & tmp$LG != "LG14",]

# Extract LG10 & LG14 from LG.crab
tmp3 <- LG.crab2[LG.crab2$LG == "LG10" | LG.crab2$LG == "LG14",]

# Merge data
LG.new <- rbind.data.frame(tmp2, tmp3)
rm(tmp, tmp2, tmp3)

# Recalculate mean and distance per contig
tmp <- LG.new[,1:4]
LG.new <- tmp %>% arrange(LG, contig) %>% 
  group_by(LG, contig) %>% 
  mutate(AvgMP = mean(av), deltaMP = abs(mean(av) - av))
rm(tmp)



### Save filtered map ####
write.table(LG.new, "ConsensusMap.v2.txt", quote = FALSE, row.names = FALSE)

### Plots ####
ggplot(LG.new, aes(x = AvgMP, y = av))+
  geom_abline(slope = 1, intercept = 0, lty = 2)+
  geom_point(colour = "blue", alpha = 0.4)+
  facet_wrap(~LG)+
  labs(x = "Mean map position (cM)", y = "Marker map position (cM)")+
  annotate("text", x = 20, y = 80, 
           label = paste("r =", round(cor(LG.new$AvgMP, LG.new$av), 4)))+
  theme_bw()
