########### Map inversions onto new map .v2 #####################
### This script updates the map positions of the inversions,
### onto the new consensus map. The original inversion positions
### were published in Westram et al. 2021, except for those on
### LG12, which were identified by Katie Hearn. The consensus
### map was generated by Eva Koch.
### Version 2 uses contigs close to the breakpoints on the old map.
### The distance from the breakpoints is defined by a new parameter
### conf.dist = the confidence distance
### James Reeve- Göteborg Universitet
### 26/11/2021

### Preparation
rm(list = ls())
options(stringsAsFactors = FALSE)
dev.off()
setwd("")

### Packages
library(tidyverse)
library(ggpubr)

### Upload data
# Crab map - note this has been filtered by Alan Le Moan
LG.crab <- read.table("Map_filtrated.txt", header = T)
LG.crab$LG <- paste0("LG", LG.crab$LG) # Change LG column to match LG.cons
# Concensus map
LG.cons <- read.table("ConsensusMap.v2.txt", header = T)
# Inversion positions
Inversions <- read.csv("/PATH/Inversion_positions_on_old_map.csv", header = T)

### Write a function to map inversion positions to new map
Inv.mapper <- function(inversion, inversion.parameters, old.map, new.map, conf.dist){
  # Subset to specific inversion
  dat <- inversion.parameters[inversion.parameters[, "INV"] == inversion, ]
  
  # Extract parameters of an inversion
  Spos <- dat[dat$Start == TRUE, "Pos"]    # Position of lower breakpoint
  Epos <- dat[dat$Start == FALSE, "Pos"]   # Position of upper breakpoint
  LG <- dat$LG[1]       # Linkage group the inversion is on
  
  # Subset old map to focal LG
  omp <- old.map[old.map[,"LG"] == LG,]
  
  # Find all contigs that map to an inversion on the old map:
  contigs <- omp[omp$av >= Spos & omp$av <= Epos, ]
  
  # Subset to contigs with a confidence distance of the inversion's breakpoints
  contigs <- contigs[contigs$av <= Spos+conf.dist | contigs$av >= Epos-conf.dist,
          "contig"]
  
  # Match with contigs on new linkage map
  tmp <- new.map[new.map[,"contig"] %in% contigs, ]
  
  # Find new min and max positions
  bpS <- min(tmp[tmp$LG == LG, "av"])
  bpE <- max(tmp[tmp$LG == LG, "av"])
  
  # Create new output with information about the new map position
  res <- data.frame("LG" = LG,
                    "Inv" = inversion,
                    "Start_pos" = bpS,
                    "End_pos" = bpE,
                    "delta_start_pos" = abs(bpS - Spos),
                    "delta_end_pos" = abs(bpE - Epos),
                    "N_contigs" = nrow(tmp),
                    "N_map_to_diff_LG" = nrow(tmp[tmp$LG != LG,]))
  
  return(res)
}

### Run the function for all inversions
Repos <- lapply(unique(Inversions$INV), Inv.mapper, 
                old.map = LG.crab, 
                new.map = LG.cons, 
                inversion.parameters = Inversions[Inversions$Site == "consensus",],
                conf.dist = 2)
Repos <- do.call(rbind.data.frame,Repos)

### Save output
write.csv(Repos, "/PATH/Inversion_positions_on_new_map_v2.csv", quote = FALSE, row.names = FALSE)

### Plot inversion positions on linkage map
tmp <- Inversions[Inversions$Site == "consensus",] %>%
  spread(key = Start, value = Pos)
colnames(tmp)[6:7] <- c("End_pos", "Start_pos")

ggplot()+
  geom_rect(data = Repos, # New map
            aes(xmin = Start_pos, xmax = End_pos, ymin = 0.1, ymax = 0.3, 
                group = Inv), colour = "darkgreen", fill = "green", alpha = 0.4)+
  geom_rect(data = tmp, # Old map
            aes(xmin = Start_pos, xmax = End_pos, ymin = -0.3, ymax = -0.1, 
                group = INV), colour = "darkred", fill = "red", alpha = 0.4)+
  geom_point(data = LG.cons, aes(x = av, y = 0.2), colour = "black")+ # New map
  geom_point(data = LG.crab, aes(x = av, y = -0.2), colour = "black")+ # Old map
  facet_wrap(~LG)+
  labs(x = "Map position (cM)")+
  scale_y_continuous(breaks = c(-0.2, 0.2), labels = c("Old map", "New map"))+
  theme_bw()+
  theme(axis.title.y = element_blank())
